# Site settings
title: Nihla Akram
description: 'Hello there! I’m Nihla, an undergraduate in Software Engineering at IIT Sri Lanka. During my free time I play CandyCrush and draw mehendi.'
baseurl: ''
#google_analytics: 'UA-74332052-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Nihla Akram'
  email: nihlaakr@gmail.com
  github_username:  nihlaakram
  linkedin_username:  nihlaakram
  #pinterest_username: diksha2895
  #twitter_username: diksha_28795
  #facebook_username: username

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
